workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m2

    integrations:
      app_store_connect: Codemagic  # App Store Connect에서 등록한 키 이름으로 변경하세요

    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.dailypace.dailyPace
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install

      - name: Build IPA
        script: |
          flutter build ipa --release \
            --build-name=1.0.2 \
            --build-number=$PROJECT_BUILD_NUMBER \
            --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
